# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fabric Properties

minecraft_version=1.21.6
yarn_mappings=1.21.6+build.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.6.6
maven_group=net.codewyrm.dwdsb
archives_base_name=dwdsb

# Dependencies
fabric_version=0.127.0+1.21.6